Attendance/Controllers/EmployeeTaskController.cs
using Attendance.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AttendanceServices.Services;
using Attendance.ViewModel;
using AttendanceData.Entities;
using System.Security.Claims;
using System.Linq;
using System;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Attendance.Misc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Attendance.Controllers
{
    [Authorize]
    public class EmployeeTaskController : Controller
    {
        private IEmployeeTaskData _data;
        private UserManager<User> _userManager;
        private AttendanceDbContext _context;
        private ITaskTodoData _tasktododata;

        //private IEmployeeData _emp_data;

        public EmployeeTaskController(IEmployeeTaskData employeeTaskData, ITaskTodoData taskTodoData, AttendanceDbContext context, UserManager<User> userManager)
        {
            _data = employeeTaskData;
            _userManager = userManager;
            _context = context;
            //_emp_data = employeeData;
            _tasktododata = taskTodoData;
        }
        // GET: EmployeeTask
        public ActionResult Index()
        {
            //var _task = from t in _context.EmployeeTasks select t;
            //int pageSize = 10;

            var userID = _userManager.GetUserId(HttpContext.User);
            ViewBag.UserID = userID;
            var emp_task = new EmployeeTaskModel();
            emp_task.employeeTasks = _data.GetAll();

            //return View(await PaginatedList<EmployeeTask>.CreateAsync(_task.AsNoTracking(),page ?? 1, pageSize));
            return View(emp_task);
        }

        // GET: EmployeeTask/Details/5
       
        public async Task<ActionResult> Details(int? id)
        {
            
            if (id == null)
            {
                _ = RedirectToAction(nameof(Index));
            }
            var model = await _context.EmployeeTasks.FirstOrDefaultAsync(x => x.ID == id);
            {
                if(model == null)
                {
                    return NotFound();
                }
            }

            return View(model);
        }

        // GET: EmployeeTask/Create
        public ActionResult Create()
        {

            var _taskType = _context.TaskTodos;
            ViewBag.TaskTodo = _taskType;
            return View();
        }

        // POST: EmployeeTask/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeTaskViewModel employeeTaskViewModel)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    var _emp_task = new EmployeeTask
                    {
                        Description = employeeTaskViewModel.Description,
                        UserId = _userManager.GetUserId(HttpContext.User),
                        TodoId = _tasktododata.GetTaskId(employeeTaskViewModel.TaskType),
                        TaskType = employeeTaskViewModel.TaskType,
                        StartDate = employeeTaskViewModel.StartDate,
                        EndDate = employeeTaskViewModel.EndDate,
                        IsComplete = employeeTaskViewModel.IsComplete, 
                        Duration = Duration(employeeTaskViewModel.StartDate, employeeTaskViewModel.EndDate)
                        
                    };
                    _data.Add(_emp_task);
                    return RedirectToAction(nameof(Index));

                }

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                var error = ex.Message;
                return View();
            }
        }

        private double Duration(DateTime startTime, DateTime endTime) => (endTime - startTime).TotalMinutes;
        

        // GET: EmployeeTask/Edit/5
        [HttpGet]
        [Authorize]
        public ActionResult Edit(int id)
        {
            var model = _data.GetById(id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
            
        }

        // POST: EmployeeTask/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, EmployeeTaskViewModel model)
        {
            
            try
            {
                var emp_task = _data.GetById(id);
                if (ModelState.IsValid)
                {
                    emp_task.IsComplete = model.IsComplete;
                    _data.Commit();
                    return RedirectToAction("Details", new { id = emp_task.ID});
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmployeeTask/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EmployeeTask/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Attendance/Views/EmployeeTask/Create.cshtml
@model Attendance.Models.EmployeeTaskModel;

@{
    ViewData["Title"] = "Add Task";
}



<h4>Employee Task</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class=" form-group">
                <input type="hidden" asp-for="TaskTodoId" asp-items="@(new SelectList(ViewBag.TaskTodo, "TaskTodoID", "Type"))"/>
            </div>
            <div class="form-group">
                <label asp-for="TaskType" class="control-label"></label>
                <select asp-for="TaskType" class="form-control"  asp-items="@(new SelectList(ViewBag.TaskTodo, "Type", "Type"))">
                    <option value="">Select Task</option>
                </select>
                <span asp-validation-for="TaskType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="EmployeeID" class="control-label"></label>
                <select asp-for="EmployeeID" class="form-control" asp-items="" />
                <span asp-validation-for="EmployeeID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsComplete" /> @Html.DisplayNameFor(model => model.IsComplete)
                    </label>
                </div>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-default" asp-action="Create" asp-controller="EmployeeTask"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Attendance/Views/EmployeeTask/Details.cshtml
@model AttendanceData.Entities.EmployeeTask

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Employee Task</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TaskType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaskType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TodoId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TodoId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsComplete)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsComplete)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Attendance/Views/EmployeeTask/Edit.cshtml
@model AttendanceData.Entities.EmployeeTask

@{
    ViewData["Title"] = "Edit Employee Task";
}

<h2>Edit @Model.TaskType</h2>

<h4>Employee Task</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="TaskType" class="control-label"></label>
                <input asp-for="TaskType" class="form-control" readonly ="@(true)"/>
                <span asp-validation-for="TaskType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsComplete" /> @Html.DisplayNameFor(model => model.IsComplete)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Attendance/Views/EmployeeTask/Index.cshtml
@using Attendance.Models

@model EmployeeTaskModel

@{
    ViewData["Title"] = "Employee Task";
}

<h2>Employee Task</h2>

<p>
    <a asp-action="Create">Add New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TaskType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.EmployeeID)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.IsComplete)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>

        @if (!User.IsInRole("Admin"))
        {
            @foreach (var item in Model.employeeTasks.Where(x => x.UserId == ViewBag.UserID).Where(x=>x.IsComplete == false))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TaskType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => item.UserId)
                        </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => item.IsComplete)
                        </td>*@
                    @*<td>
                            <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                        </td>*@
                </tr>
            }
        }
        else
        {
            @foreach (var item in Model.employeeTasks.Where(x=>x.IsComplete==false))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TaskType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => item.UserId)
                        </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.IsComplete)
                    </td>*@
                    <td>
                        <a class="btn btn-default btn-sm active" role="button" aria-pressed="true" asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a class="btn btn-default btn-sm active" role="button" aria-pressed="true" asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a class="btn btn-default btn-sm active" role="button" aria-pressed="true" asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
            }
        }

    </tbody>
</table>
@*@{var index = Attendance.Misc.PaginatedList<EmployeeTaskModel>.PageIndex + 1 }
<a class="btn" asp-action="Index" asp-route-page="@(Attendance.Misc.PaginatedList<EmployeeTaskModel>.PageIndex)"></a>*@